import fs from "node:fs";
import path from "node:path";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react-swc";
import { defineConfig } from "vitest/config";

/** Read the synced build manifest generated by scripts/sync-app-version.mjs. */
function readAppVersion(): number {
  const versionPath = path.resolve(__dirname, "public/version.json");
  if (fs.existsSync(versionPath)) {
    try {
      const parsed = JSON.parse(fs.readFileSync(versionPath, "utf8")) as {
        version?: unknown;
      };
      if (typeof parsed.version === "number" && Number.isFinite(parsed.version)) {
        return parsed.version;
      }
    } catch {
      // Fall through to changelog.json.
    }
  }

  const changelogPath = path.resolve(__dirname, "public/changelog.json");
  const parsed = JSON.parse(fs.readFileSync(changelogPath, "utf8")) as {
    version?: unknown;
  };
  return typeof parsed.version === "number" && Number.isFinite(parsed.version)
    ? parsed.version
    : 0;
}

const appVersion = readAppVersion();

// https://vite.dev/config/
export default defineConfig({
  define: {
    __APP_CHANGELOG_VERSION__: JSON.stringify(appVersion),
  },
  plugins: [react(), tailwindcss()],
  worker: {
    format: "es",
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  test: {
    // Pure logic / data tests: no JSDOM unless a module needs it.
    environment: "node",
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
    passWithNoTests: true,
  },
});
